### PR TITLE
Proposal to allow ModelWrapper and Filter to operate in different coordinate systems

### PR DESCRIPTION
**Pull request by WardLT**
A proposal to help with #59

- [ ] Split off transform to its own class
- [ ] Introduce transform class as argument to ModelWrapper
- [ ] Update the MvRD to have a transform operation which produces a new distribution after applying a transform
- [ ] Allow the `get_state` function of the estimator to detect when the state used by an underlying filter requires a transformation

### CODE REVIEW

**Comment by victorventuri** [comment]
Jotting down some notes here: 

- the `TransformedModel` class has methods like `transform_covariance_to_wrapped`, which implies that it knows at least what the underlying probability distribution is. 
    - at first, this doesn't seem like quite a problem, as all pdfs have a covariance, but the problem is that it becomes the responsibility of the `TransformedModel` to know how to update that
    - to me, this clashes with the modularity idea: the wrappers should similarly be agnostic to the `BaseFilter` being used, and be able to work with standard KF, extended KF (neither of these implemented), UKF, particle filters, RNN-based filters, etc. 
- given we are creating this functionality in the `TransformedModel`, I feel like the `TransformedFilter` is superfluous: its only "new" functionality is to return the state de-transformed, but that can be done at the `OnlineEstimator` level, since that has access to the necessary functions, and is the user-facing object.
- I see you have a `TODO (wardlt): Move this whole module to the ./filters/ package?`, which is a sentiment i agree with (though maybe this was a leftover from an older branch?). since the `ModelWrapper` is the way the `BaseFilter`s expect to interact with models, I liked having it defined in the `filters` directory

**Comment by WardLT** [comment]
> The TransformedModel class has methods like transform_covariance_to_wrapped, which implies that it knows at least what the underlying probability distribution is.
Yea, that is a bit of a problem. I'm eager to see your thoughts on how to make the MVP classes allow transformations. 

> ... given we are creating this functionality in the TransformedModel, I feel like the TransformedFilter is superfluous: its only "new" functionality is to return the state de-transformed, but that can be done at the OnlineEstimator level, since that has access to the necessary functions, and is the user-facing object.
Agreed. The primary user of the `TransformedFilter` is so that the OnlineEsimator code need not be changed to allow for transformation, but perhaps there's a simple way to do that. 

> I see you have a TODO (wardlt): Move this whole module to the ./filters/ package?, which is a sentiment i agree with (though maybe this was a leftover from an older branch?)
It's actually something new that came up while I was trying to consolidate the model-wrapper-related stuff to the same module, and also to promote it from a generic "utils" given it's large importance in implementing a filter.

**Comment by victorventuri** [comment]
Ok, so I came up with something for the `MvRD`. Looking forward to sharing it with you in a bit, and getting your feedback. I was doing it in the `demonstrate_ignorance.ipynb` notebook (which is naturally ignored) to test it out, since i didn't feel like making a full new branch for it, given there's a good chance it would go nowhere. I think once we sync up today, we should just create a `asoh_normalization` branch to work on whichever solution we come up with. What do you think?

**Comment by WardLT** [comment]
Let's do it :)

**Comment by WardLT** [comment]
Closed in favor of a different branch

**Pull request closed without merging**
