### PR TITLE
Base definitions for online estimators

### PR DESCRIPTION
**Pull request by victorventuri**
Here, we have base definitions for online estimators. The main idea is that the estimators should be fully numeric, and totally agnostic to the models being used (though they must know what numbers/`numpy.ndarray`s are inputs, hidden states, and outputs, of course).

 We have a `MultivariateRandomVariable` class, which is used to describe hidden states and measurements (maybe also inputs, but I don't know how to properly do that yet). We also establish a class to facilitate the interface between `CellModel`s and the estimators.

### CODE REVIEW

**Comment by WardLT** [comment]
Could you show me how one creates a `OutputMeasurement` class? I'm still unsure why it needs to exist separately from an `OutputQuantities` if both represent kind of the same thing.

**Comment by victorventuri** [comment]
The main idea is that the `OutputQuantities` is a deterministic output specific to the `CellModel`, while the `OutputMeasurements` is a random variable (so it would, for example, include mean and variance in the case of a Gaussian). Effectively, the `OutputMeasurements` acts as an interface between the "physics"-based `OutputQuantities` and the statistics-based estimator.

**Comment by WardLT** [comment]
Ok, that makes sense. It seems sensible enough to keep measurements and model outputs separate for now, but I'm going to keep an eye open for an opportunity or reason to reduce complexity by merging the two.

**Comment by victorventuri** [comment]
Sounds good! I think the best place to re-evaluate the distinction might be when we do the minor revamp for optimizing batches of hidden states (like from sigma points)

**Pull request merged**
